services:
  - type: web
    name: metrolist-sync-relay
    env: docker
    plan: free
    dockerfilePath: ./relay-server/Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
